
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo KBS terraform
  displayName: 'Run a one-line script'
- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    backendType: 'azurerm'
    backendServiceArm: 'RamyaSubscription (76fff363-1629-4001-aaa0-9d3f16bf4e64)'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-backend-rg'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'terraformstorage123'
    backendAzureRmContainerName: 'terraformstorage123container'
    backendAzureRmKey: 'kubernetes-dev.tfstate'
- task: TerraformCLI@0
  inputs:
    command: 'init'
    commandOptions: '-var client_id=${client_id)  -var client_secret=${client_secret} -var ssh_keys=${publickey.secureFile}'
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_example_rsa.pub'